(() => {
  const body = document.body;
  const baseUrl = body.dataset.chatwootBaseUrl?.replace(/\/$/, "") || "";
  const websiteToken = body.dataset.chatwootToken || "";
  const panel = document.getElementById("chat");
  const bodyMessages = document.getElementById("chat-messages");
  const quickMenu = document.getElementById("quick-menu");
  const input = document.getElementById("chat-input");
  const form = document.getElementById("chat-form");
  const conversationHistory = [];
  const replies = { products: "目前有演示款桌面灯和演示款随行杯。你可以告诉我使用场景和预算，我帮你缩小选择范围。", prices: "演示款桌面灯 ¥199 起，演示款随行杯 ¥129 起。最终价格以商品卡片和人工确认结果为准。", hours: "人工客服营业时间：周一至周五 09:00–18:00，周六 10:00–17:00。非营业时间我会先帮你记录需求。", human: "好的，我已记录人工咨询需求。营业时间内会有客服接管；如果你愿意，也可以先留下想了解的产品。" };
  const productReplies = { light: { text: "这款是演示款桌面灯，暖光、三档调节、USB-C 供电，适合书桌和床头使用。", image: "/assets/demo-light.png", title: "演示款桌面灯", price: "¥199 起", meta: "暖光 · 三档调节 · USB-C" }, tumbler: { text: "这款随行杯容量 450ml，适合通勤和日常饮水，想了解颜色或优惠我可以继续帮你确认。", image: "/assets/demo-tumbler.png", title: "演示款随行杯", price: "¥129 起", meta: "保温 · 便携 · 450ml" } };
  const appendMessage = (text, role = "agent", product = null) => { const row = document.createElement("div"); row.className = `message-row ${role === "user" ? "user-row" : "agent-row"}`; if (role !== "user") { const avatar = document.createElement("span"); avatar.className = "mini-avatar"; avatar.textContent = "示"; row.appendChild(avatar); } const bubble = document.createElement("div"); bubble.className = `message-bubble ${role === "user" ? "user-bubble" : "agent-bubble"}`; const p = document.createElement("p"); p.textContent = text; bubble.appendChild(p); if (product) { const title = product.title || product.name; const meta = product.meta || (product.features || []).join(" · "); const card = document.createElement("div"); card.className = "inline-product"; card.innerHTML = `<img src="${product.image}" alt="${title}" /><div><strong>${title}</strong><span>${meta}</span><b>${product.price}</b></div>`; bubble.appendChild(card); } const time = document.createElement("span"); time.className = "message-time"; time.textContent = "刚刚"; bubble.appendChild(time); row.appendChild(bubble); bodyMessages.appendChild(row); conversationHistory.push({ role: role === "user" ? "user" : "assistant", content: text }); bodyMessages.parentElement.scrollTop = bodyMessages.parentElement.scrollHeight; };
  const respond = (key) => { const button = document.querySelector(`[data-action="${key}"]`); appendMessage(button?.textContent || "继续了解", "user"); const item = productReplies[key]; window.setTimeout(() => appendMessage(item?.text || replies[key], "agent", item || null), 240); };
  const openChat = () => { panel.classList.add("is-visible"); panel.setAttribute("aria-hidden", "false"); document.getElementById("chat-launcher").classList.add("is-hidden"); input.focus(); if (websiteToken && window.$chatwoot) window.$chatwoot.toggle("open"); };
  const closeChat = () => { panel.classList.remove("is-visible"); panel.setAttribute("aria-hidden", "true"); document.getElementById("chat-launcher").classList.remove("is-hidden"); };
  if (websiteToken && baseUrl) { const script = document.createElement("script"); script.src = `${baseUrl}/packs/js/sdk.js`; script.async = true; script.onload = () => window.chatwootSDK.run({ websiteToken, baseUrl }); document.head.appendChild(script); }
  document.getElementById("start-chat").addEventListener("click", openChat); document.getElementById("chat-launcher").addEventListener("click", openChat); document.getElementById("chat-close").addEventListener("click", closeChat); document.getElementById("chat-minimize").addEventListener("click", closeChat); document.querySelector(".context-close").addEventListener("click", (event) => event.currentTarget.parentElement.remove());
  document.querySelectorAll(".product-ask").forEach((button) => button.addEventListener("click", () => { openChat(); window.setTimeout(() => { appendMessage(button.textContent, "user"); const item = productReplies[button.dataset.product]; window.setTimeout(() => appendMessage(item.text, "agent", item), 240); }, 80); }));
  quickMenu.addEventListener("click", (event) => { const button = event.target.closest("button"); if (button) respond(button.dataset.action); });
  form.addEventListener("submit", async (event) => { event.preventDefault(); const value = input.value.trim(); if (!value) return; const history = conversationHistory.slice(-10); appendMessage(value, "user"); input.value = ""; input.disabled = true; try { const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: value, history }) }); if (!response.ok) throw new Error("chat request failed"); const data = await response.json(); appendMessage(data.message, "agent", data.products?.[0] || null); } catch { appendMessage("网络暂时开小差了。你可以使用快捷菜单，或稍后再试。", "agent"); } finally { input.disabled = false; input.focus(); } });
  document.addEventListener("keydown", (event) => { if (event.key === "Escape" && panel.classList.contains("is-visible")) closeChat(); });
})();
